### ISSUE TITLE
Is there a machine learning model that simplifies the generation of small-size chinese fonts

### ISSUE THREAD

**Issue by ghost** [IShengFang/TypographyResearchCollection#1]
Is there a machine learning model that simplifies the generation of small-size chinese fonts.

For example, rendering a "魔" character into a 10*10 square. At this time, it is necessary to regenerate the font, simplify some outlines, and make it look better when rendered;

**Comment by IShengFang** [comment]
To the best of my knowledge, there is no work for the small-size CJKV font generation.
The traditional solution is font hinting which is the rule for rendering small-size glyphs.
I hope the above is useful to you.
If you have seen any related work, please share with me. 😄

**Comment by ghost** [comment]
Thanks very much.
